docker container stop producer
docker container stop grafana
docker container stop cassandra1
docker container stop spark-worker-c
docker container stop spark-worker-b
docker container stop spark-worker-a
docker container stop spark-master
docker container stop kafdrop
docker container stop kafka
docker container stop zookeeper